sugarcube-2:
  macros:
    AffectionChange:
      name: AffectionChange
      parameters:
        - string &+ number
    AppearanceCorrect:
      name: AppearanceCorrect
      parameters:
        - ""
    BodyHeightText:
      name: BodyHeightText
      parameters:
        - ""
    CarryAdjust:
      name: CarryAdjust
      parameters:
        - ""
    CheckParty:
      name: CheckParty
      parameters:
        - ""
    checkTime:
      name: checkTime
      parameters:
        - ""
    CloneSelf:
      name: CloneSelf
      parameters:
        - ""
    CollectRelic:
      name: CollectRelic
      parameters:
        - var
    ConversationChoices:
      name: ConversationChoices
    createGolem:
      name: createGolem
      parameters:
        - "'male'|'female' &+ 'clay'|'snow'|'doll'|'water'|'skeleton'"
    CurseGrid:
      name: CurseGrid
      parameters:
        - string
    dollTF:
      name: dollTF
      parameters:
        - ""
    Equipment:
      name: Equipment
      parameters:
        - ""
    FlaskFirst:
      name: FlaskFirst
      parameters:
        - ""
    ForagingGrid:
      name: ForagingGrid
      parameters:
        - var |+ ...var
    ForagingGridNarrow:
      name: ForagingGrid
      parameters:
        - var |+ ...var
    GenderPronoun:
      name: GenderPronoun
      parameters:
        - ""
    HabitationGrid:
      name: HabitationGrid
      parameters:
        - var |+ ...var
    Handicap:
      name: Handicap
      parameters:
        - ""
    HornGrowthDesc:
      name: HornGrowthDesc
      parameters:
        - var|string &+ number
    Inhuman:
      name: Inhuman
      parameters:
        - ""
    LeveledCurseDescription:
      name: LeveledCurseDescription
      parameters:
        - var|string
    Lewdness:
      name: Lewdness
      parameters:
        - ""
    MonsterPregCheckParty:
      name: MonsterPregCheckParty
      parameters:
        - ""
    mrms:
      name: mrms
      parameters:
        - ""
    Numerical:
      name: Numerical
      parameters:
        - var|number &+ (string |+ string)
    ObjectivePronoun:
      name: ObjectivePronoun
      parameters:
        - ""
    PassTime:
      name: PassTime
      parameters:
        - var|number
    PassTimeWithEvents:
      name: PassTimeWithEvents
      parameters:
        - ""
    PenisLengthText:
      name: PenisLengthText
      parameters:
        - "|+ bool"
    PerceivedGender:
      name: PerceivedGender
      parameters:
        - var
    PerceivedGender2:
      name: PerceivedGender2
      parameters:
        - var
    PerceivedRace:
      name: PerceivedRace
      parameters:
        - var
    PerceivedStature:
      name: PerceivedStature
      parameters:
        - var
    PluralS:
      name: PluralS
      parameters:
        - var|number
    PossesivePronoun:
      name: PossesivePronoun
      parameters:
        - ""
    PregCheck:
      name: PregCheck
      parameters:
        - ""
    PregCheckTentacle:
      name: PregCheckTentacle
      parameters:
        - var
    PreviewTravelTime:
      name: PreviewTravelTime
      parameters:
        - string &+ var|number |+ var|number |+ var|number
    Pronoun:
      name: Pronoun
      parameters:
        - ""
    randomSexSelect:
      name: randomSexSelect
      parameters:
        - ""
    RelicGrid:
      name: RelicGrid
      parameters:
        - string
    RemoveCurse:
      name: RemoveCurse
      parameters:
        - var
    say:
      name: say
      container: true
      parameters:
        - var |+ string
    SemenDemonCalc:
      name: SemenDemonCalc
      parameters:
        - var|number
    ShowAge:
      name: ShowAge
      parameters:
        - var|number
    sirmaam:
      name: sirmaam
      parameters:
        - ""
    StartTraveling:
      name: StartTraveling
      parameters:
        - var|number |+ var|number |+ var|number |+ string |+ 'preview'
    Threat1Criterion:
      name: Threat1Criterion
      parameters:
        - ""
    ThreatGrid:
      name: ThreatGrid
      parameters:
        - var |+ ...var
    TravelToPassage:
      name: TravelToPassage
      parameters:
        - var|string &+ var|string &+ var|number |+ var|number |+ var|number |+
          string
    UpdateAttributes:
      name: UpdateAttributes
      parameters:
        - ""
    Update_Misc_Stat:
      name: Update_Misc_Stat
      parameters:
        - ""
    volume:
      name: volume
      parameters:
        - ""
    WaitAtPassage:
      name: WaitAtPassage
      parameters:
        - var|string &+ var|string &+ number|string |+ string
    WonderGrid:
      name: WonderGrid
      parameters:
        - var |+ ...var
    WonderGridGold:
      name: WonderGridGold
      parameters:
        - var |+ ...var
    printHTML:
      name: printHTML
    bordered:
      name: bordered
      container: true
      parameters:
        - string |+ string
    SettlementGrid:
      name: SettlementGrid
    PronounPerceivedGender:
      name: PronounPerceivedGender
    ascensionCosts:
      name: ascensionCosts
    descentTime:
      name: descentTime
    showAvailableConversations:
      name: showAvailableConversations
    showShrineInteractions:
      name: showShrineInteractions
    BanditThreat:
      name: BanditThreat
    sidebar-widget:
      name: sidebar-widget
    TravelToPassageButton:
      name: TravelToPassageButton
    WaitAtPassageButton:
      name: WaitAtPassageButton
    LinkButton:
      name: LinkButton
      container: true
